
"use client";

import { useState, type FormEvent } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter, DialogClose } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useForm, type SubmitHandler } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";

interface AddChildModalProps {
  isOpen: boolean;
  onClose: () => void;
  onChildAdded?: () => void; // Optional callback to refresh child list
}

const childFormSchema = z.object({
  name: z.string().min(2, { message: "Name must be at least 2 characters." }).max(50, { message: "Name must be less than 50 characters." }),
  email: z.string().email({ message: "Invalid email address." }),
  // Password will be auto-generated by the backend or set separately. Not part of this form for simplicity.
});

type ChildFormValues = z.infer<typeof childFormSchema>;

export default function AddChildModal({ isOpen, onClose, onChildAdded }: AddChildModalProps) {
  const { signUpChildAndLinkToParent, user } = useAuth();
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);

  const { register, handleSubmit, formState: { errors }, reset } = useForm<ChildFormValues>({
    resolver: zodResolver(childFormSchema),
    defaultValues: {
      name: "",
      email: "",
    }
  });

  const processSubmit: SubmitHandler<ChildFormValues> = async (data) => {
    if (!user) {
      toast({ title: "Error", description: "Parent not authenticated.", variant: "destructive" });
      return;
    }
    setIsSubmitting(true);
    try {
      // The password field is intentionally omitted from the form.
      // signUpChildAndLinkToParent in AuthContext handles child creation logic,
      // potentially auto-generating a password or setting up the account
      // in a way that doesn't require immediate password input from the parent here.
      const result = await signUpChildAndLinkToParent(user.uid, { name: data.name, email: data.email });
      if (result) {
        toast({ title: "Child Added Successfully", description: `${data.name} has been added to your family.` });
        reset();
        onClose();
        if (onChildAdded) {
            onChildAdded(); // Trigger refresh if callback provided
        }
      } else {
        throw new Error("Failed to add child. Please try again.");
      }
    } catch (error: any) {
      toast({ title: "Failed to Add Child", description: error.message || "An unexpected error occurred.", variant: "destructive" });
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleCloseDialog = () => {
    if (!isSubmitting) {
      reset();
      onClose();
    }
  };

  if (!isOpen) return null;

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && handleCloseDialog()}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Add New Child</DialogTitle>
          <DialogDescription>
            Enter the details for the new child. Their account will be linked to yours.
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit(processSubmit)} className="grid gap-6 py-4">
          <div className="space-y-2">
            <Label htmlFor="name">Child's Name</Label>
            <Input id="name" {...register("name")} placeholder="e.g., Alex Smith" className={errors.name ? "border-destructive" : ""} />
            {errors.name && <p className="text-sm text-destructive">{errors.name.message}</p>}
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Child's Email</Label>
            <Input id="email" type="email" {...register("email")} placeholder="e.g., alex@example.com" className={errors.email ? "border-destructive" : ""} />
            {errors.email && <p className="text-sm text-destructive">{errors.email.message}</p>}
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" onClick={handleCloseDialog} disabled={isSubmitting}>Cancel</Button>
            <Button type="submit" disabled={isSubmitting}>
              {isSubmitting ? "Adding..." : "Add Child"}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
